### ISSUE TITLE
Impossible to install in dokuwiki admin

### ISSUE THREAD

**Issue by phil123456** [splitbrain/dokuwiki-plugin-dw2pdf#252] opened 2017-02-01 08:47 UTC
Hello

If I try to install your pluggin :

      Unable to download the file: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master

if I try a manual install with

      https://github.com/splitbrain/dokuwiki-plugin-dw2pdf.git

I get "Header does not match it's checksum"

**Comment by phil123456** [comment] 2017-02-09 06:34
anyone ?????

**Comment by greldinard** [comment] 2017-02-10 10:48
I can confirm this problem. I downloaded the tar.gz file and extracted it manuall to lib/plugins of the wiki directory according to the manual installation instructions. After applying correct permissions it worked fine for me. It seems there is some problem with PlugIn-Manager, download size is nearly 50 MB so it's probably too big for PlugIn-Manager. As I recall there already has been a problem like that in the past. Hope that helps...

**Comment by phil123456** [comment] 2017-02-10 11:35
so how do I solve this ?you start talking about permissions, then you say it's a file size issue ?

**Comment by greldinard** [comment] 2017-02-10 12:02
For me following steps worked:

- Download https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master
- Copy to DokuWiki servers
- Extract the archive
- Rename the extracted folder to dw2pdf
- Set permissions so the webserver can work with it (chown -R www-data:www-data dw2pdf)
- Move the folder to <dokuwiki_installation_dir>/lib/plugins
- Reload the page in the browser and - voilá - the plugin is installed

I hope it will work for you too.

**Comment by phil123456** [comment] 2017-02-10 12:35
ok so it's manual manual install :-)
thanks I'll give it a try

**Comment by Klap-in** [comment] 2017-11-12 15:58
Since the used library mPDF is updated to version 6 it has a download package of at least 50 MB.

See proposed solution in #194.

**Comment by Klap-in** [comment] 2017-11-29 20:44
Closed in favor of #194

**Closed by Klap-in** 2017-11-29 20:44 UTC
