### ISSUE TITLE
No way to include images in pdf

### ISSUE THREAD

**Issue by aDDokuwikiUser** [splitbrain/dokuwiki-plugin-dw2pdf#177] opened 2015-03-13 14:40 UTC
I just installed dokuwiki and its extensions a couple of days ago, so I'm using the current version of all stuff.

Unfortunaltely for me there is no way to include an image in a pdf. This is true for
- .png, .jpg, .gif formats. No matter if with or withour alpha channel or EXIF information.
- all sizes I've tried from tiny to large.
  
  My Dokuwiki is running on Windows server 2013

Maybe you could provide an example image from which you know that it gets rendered in the pdf.

Regards

Michael

**Comment by splitbrain** [comment] 2015-03-16 15:43
Images should work just fine. Eg. Try exporting wiki:syntax

You should make sure, your wiki's server has libGD available (AFAIK DokuWiki's imagemagick support does not work within dw2pdf).

**Comment by aDokuwikiUser** [comment] 2015-03-23 09:13
Sorry to come back with this, but what I can tell you is:

1. libGD is installed, the following page in my local installation works fine: 
<?php
$bild = imagecreatetruecolor(200,250);
imagejpeg($bild, "test.jpg");
?>
<img src="test.jpg" />

(taken from http://www.schattenbaum.net/php/bild_mit_php.php, a website that teaches basic usage of libGD)

2. I copied the mpdf examples directory from a fresh www.mpdf1.com-download to the mpdf that you ship along with dw2pdf. The examples work fine and the images show up in the resulting pdf page.

3. I did a new dokuwiki installation with solely dw2pdf installed to eliminate the risk of plugin interference. Same result.

4. >Images should work just fine. Eg. Try exporting wiki:syntax
>>Sorry, don't know what you mean by that.
I didn't find anything that gives me an indication to "wiki:syntax"

But still dw2pdf does not show any images. Once again, I simply can't figure out what's going wrong.  Is there a log mode available? In witch php-file should I start inserting log messages to isolate the cause? Any help appreciated!

Regards

Michael

**Comment by Klap-in** [comment] 2015-03-23 22:20
See for the debugging options of mPDF library: http://mpdf1.com/manual/index.php?tid=245

You can get the html output of the dw2pdf (that what is inputted in mPDF) by an url parameter. Firstly, you have to enable the DokuWiki debugging setting (https://www.dokuwiki.org/config:allowdebug). Secondly add `&debughtml=text` (for plain text) or `&debughtml=html` (for html version that is displayed by browser) to the url that is used to initiate the pdf-export.

**Comment by aDokuwikiUser** [comment] 2015-03-24 15:31
Thanks a lot for this information. I did that. The resulting html page shows the images. In plain text there are some meta information regarding mpdf (pagebreak and such things).
I tried to feed the html to mpdf. But this results only in a blank pdf so far.

Please continue!

**Comment by aDokuwikiUser** [comment] 2015-04-13 13:25
I did a new clean install with only dw2pdf extension added (about 12 meg in size zipped). The playground page just includes the dokuwiki png image. It doesn't show up in the resulting pdf page. And I have a phpinfo() output.

Do you want me to forward this information to you? If so, please let me know how (i.e. public ftp server or dropbox).

Thanks again.

Michael

**Comment by aDokuwikiUser** [comment] 2015-04-14 06:48
Now finally, the space character is it. dw2pdf actually seems not to be able to deal with blank characters being part of the server's installation path.

The pictures that are linked directly to now just print fine.

Having said that leads to two other topics, one that is known since late 2012:
The graphics produced the graphviz plugin do not get rendered in the pdf, please see https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/43

The other exists with the wrap plugin, i.e. "<warp important>This is important</wrap>" does not get displayed in the pdf as in the browser (colored and with that little picture).

Sorry folks, I'm far from bothering you :), you're writing beautiful software that works great. Guess combining features of different plugins is a big challenge. Any chance to have that fixed?

Regards 

Michael

**Comment by Klap-in** [comment] 2015-04-14 12:19
Thanks for pointing out the cause! That is useful input for further
investigation.


NB: Please add your notes with respect to graphviz or wrap plugin to their
respectively issue reports (or start a specific one). Mixing topics is
confusing.

2015-04-14 8:48 GMT+02:00 aDokuwikiUser <notifications@github.com>:

**Comment by Klap-in** [comment] 2017-11-22 21:28
Summary: 
a dw2pdf setup at a Windows server 2013, which had a space in the installation path, could not handle pictures.

Closing as solved, but could be an issue to double check for image issues.

**Closed by Klap-in** 2017-11-22 21:28 UTC
Labels: needinfo
