### ISSUE TITLE
Wrap-plugin with pagebreak

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [splitbrain/dokuwiki-plugin-dw2pdf#149] opened 2014-11-14 15:36 UTC
Hi,

in combination with the wrap plugin there is the following problem: 

When you use the pagebreak command
  < WRAP pagebreak> < /WRAP>
the noprint command 
  < WRAP noprint> ... < /WRAP>
on the same page is ignored.

Regards
Juergen

**Comment by Juergen-aus-Koeln** [comment] 2015-01-05 10:06
Hi,

as soon as file `cover.html` exists (without any content), the `wrap_noprint` command doesn't function any more.

Regards
Juergen

**Comment by Klap-in** [comment] 2015-01-05 10:37
If `cover.html` exists, then it is added and subsequently a `<pagebreak />` tag is included
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/action.php#L450

Pagebreaks and noprint instructions seems to conflict in the mpdf library used by this plugin. It will not be supported, or the mpdf library should be fixed.

**Comment by Juergen-aus-Koeln** [comment] 2015-04-02 09:08
But as I can see on the homepage of mpdf the pagebreak is supported. Could there be a workaround for example with html code which is embedded on the wiki page?

**Comment by Klap-in** [comment] 2015-04-02 18:04
If you have one pagebreak or such of instruction it is fine. But with a combination of that such instructions will break in mPDF something...

See here some info I collected before: http://www.mpdf1.com/forum/discussion/2286

You could try to create a simple as possible case, which shows the problem, and use it to open the dialog with the author of mpdf.

**Comment by Klap-in** [comment] 2017-11-16 19:31
Please see solution suggestion in #99.

Duplicate of #99

**Closed by Klap-in** 2017-11-16 19:31 UTC
Labels: bug
