### ISSUE TITLE
DW2PDF Plugin无法下载

### ISSUE THREAD

**Issue by CandyPockets** [splitbrain/dokuwiki-plugin-dw2pdf#222] opened 2016-02-17 08:17 UTC
你好 。
我是一个中国人。很抱歉我英语不好。只能用中文给你写信。
我目前使用docuwiki部署了一个企业内部的资源共享平台。我希望使用您的插件来导出PDF文件。但是我无法下载您的插件。我想了解为什么我不能下载。
冒昧打扰。还望见谅。
How are you.
I am a Chinese.I'm sorry my English is poor.Can only use Chinese to write to you.
I am currently using docuwiki deployed an internal resource sharing platform.I want to use your plugin to export PDF files.But I can't download your plugin.I want to know why I can't download.
I hope I didn't disturb you.

**Comment by splitbrain** [comment] 2016-02-19 11:42
possibly duplicate of #219 and #214

**Closed by splitbrain** 2016-02-19 11:42 UTC
