### ISSUE TITLE
Timestamp in pdf is not in accordance with the dokuwiki timezone

### ISSUE THREAD

**Issue by danielraknes** [splitbrain/dokuwiki-plugin-dw2pdf#268] opened 2017-04-19 10:04 UTC
I would like the timestamp @DATE@ and @UPDATE@ in the pdf do be the same as the time/timezone that I have chosen for my dokuwiki, not unix-timetamp. Can you please fix this? 

Or if this can be an option in the configuration manager I will be very happy :)

**Comment by vincentkersten** [comment] 2017-06-06 10:00
Daniel, second that, I don't know how much yours is off, mine is one hour behind:
 11:29 becomes 10:29h in the pdf footer. Maybe it just did not get 'localized time'? 

I am in: Current:  CEST
 Central European Summer Time
Next Change:  CET
 Central European Time
Current Offset:  UTC/GMT +2 hours
(see: https://www.timeanddate.com )

How much is yours off?

**Comment by vincentkersten** [comment] 2017-06-06 10:02
duplicate of: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/239 ?

**Comment by danielraknes** [comment] 2017-06-22 11:50
Mine is also one hour behind. It is similar to #239 but it does not solve the problem.

**Comment by Klap-in** [comment] 2017-11-12 22:35
The mPDF library, used by dw2pdf plugin, changes the timezone for certain situations. The last release included some improvements.

Could you test if the latest version of dw2pdf still shows this behaviour? Thanks!

**Comment by danielraknes** [comment] 2017-11-13 08:02
Now it's working great :) Thanks!




Mvh


Daniel







On Sun, Nov 12, 2017 at 11:35 PM +0100, "Gerrit Uitslag" <notifications@github.com> wrote:












The mPDF library, used by dw2pdf plugin, changes the timezone for certain situations. The last release included some improvements.


Could you test if the latest version of dw2pdf still shows this behaviour? Thanks!

**Comment by Klap-in** [comment] 2017-11-13 12:34
Nice to know!

**Closed by Klap-in** 2017-11-13 12:34 UTC
