### ISSUE TITLE
request: tpl directory by namespace

### ISSUE THREAD

**Issue by jheidecker** [splitbrain/dokuwiki-plugin-dw2pdf#183] opened 2015-04-15 00:31 UTC
Either built-in or as an option it would be nice to have the tpl match the namespace to create a tpl for each namespace. Eg:

action.php:737

``` php
                //added to match templates to namespace when available
                $params = array('do' => 'export_pdf','tpl' => getNS($ID));
                //$params = array('do' => 'export_pdf');
```

The above works for me, but I did not test with anything other than a single level of namespaces.

**Comment by MarcBeutler** [comment] 2015-08-26 07:30
It would be great to get an option that I can include at the beginning of a page, e.g:

~~PDF-TPL:yourtemplate~~

**Comment by Klap-in** [comment] 2017-12-11 18:56
Duplicate of #307

**Closed by Klap-in** 2017-12-11 18:56 UTC
Labels: feature
