### ISSUE TITLE
Bullets in Tables

### ISSUE THREAD

**Issue by lrosdahl** [splitbrain/dokuwiki-plugin-dw2pdf#259] opened 2017-03-06 21:06 UTC
I'm using your plugin for a project I'm working on and love it. It formats things beautifully, for the most part. I am having trouble with bullets in a table, however (see attached). I'm able to pinpoint some things with CSS (like aligning the text in the table to the left and top of the cells), but for some reason, I can not get the bullets to not display (or display properly). I've added a class using jQuery, which does add the class, but the CSS doesn't make any changes to the PDF.

On a (maybe) related note, I'm unable to get a pdf.css file properly working from the tpl folder where I created a pdfstyles folder (and have selected it in the config file). I'm having to use a style.local.css file in the conf folder of the plugin, which is fine, but didn't know if that might have something to do with it.

Finally, I find the following reference on line 3071 of the changelog (in case this has something to do with it): fn. OpenTag() [LI] $this->blockjustfinished=false to prevents newline after first bullet of list within table

Any help would be greatly appreciated.

Thanks so much for your excellent plugin.
[example.pdf](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/files/822513/example.pdf)

**Comment by Klap-in** [comment] 2017-03-06 22:28
- not all css is exactly supported in the library mPDF used by the dw2pdf for creating the pdf. See https://mpdf.github.io/css-stylesheets/supported-css.html for details
- anything done with javascript will never be fed into the mPDF (html created by DokuWiki is never touch by javascript, because it doesn't reach a browser or something with javascript support)
- note that the print style of your page is used as basis for the pdf (and not the screen style as normally shown as website). The print view can be shown by looking in the print previewer of your browser.
- there are some options to show the html code that is fed into mPDF. For more details see https://www.dokuwiki.org/plugin:dw2pdf#how_to_collect_more_debug_info
- other plugins than dw2pdf which provide print styling could use `print.css` or pdf specific css styling  could use `pdf.css` in their plugin folder.
- if you create a [pdf template](https://www.dokuwiki.org/plugin:dw2pdf#pdf_templates), you could add a [style](https://www.dokuwiki.org/plugin:dw2pdf#styles) by adding a style.css in the pdf-template folder.
- your last note about line 3071 is unclear. Please provide at least an exact file path, or better a pointer to code here at github.

**Comment by lrosdahl** [comment] 2017-03-07 14:02
Thank you so much for the response. I haven't tried using the debugger, so I'll give that a go. 

As far as the template is concerned (just to make sure I have it right -- I think I do), I created a folder in ~\lib\plugins\dw2pdf\tpl called pdfstyles. Then add the style.css file to that and make sure that in the configurations, pdfstyles is selected rather than default.

The changelog.txt file (here: dokuwiki-plugin-dw2pdf/mpdf/CHANGELOG.txt) has a change documented on line 3071 that references bullets and tables. I wasn't sure if that might be something that might be causing the bullets in the table to act strangely.

I really appreciate you taking the time to address my question. I will see if I can figure out how to fix the bullets through debugging.

Once again, I just want to thank you for your work on this plugin. It's great.

**Comment by Klap-in** [comment] 2017-11-20 22:07
Closing as I do not notice further action points. If you reopen, please add also an small example which allows us to reproduce the situation.

**Closed by Klap-in** 2017-11-20 22:07 UTC
