### ISSUE TITLE
Render.php : emaillink and locallink functions are not compatible with PHP7 syntax

### ISSUE THREAD

**Issue by blacklord049** [splitbrain/dokuwiki-plugin-dw2pdf#225] opened 2016-02-19 11:08 UTC
Config page requires the following syntax : 
- emaillink($address, $name = NULL, $returnonly = false)
- locallink($hash, $name = NULL, $returnonly = false)

**Comment by splitbrain** [comment] 2016-02-19 11:41
duplicate of #217

**Closed by splitbrain** 2016-02-19 11:41 UTC
