### ISSUE TITLE
open_basedir restriction violation

### ISSUE THREAD

**Issue by xi** [splitbrain/dokuwiki-plugin-dw2pdf#448] opened 2022-01-06 12:51 UTC
I was unable to open a enerated PDF file because it started with a few lines of PHP warnings like this:

```html
<br />
<b>Warning</b>:  is_file(): open_basedir restriction in effect. File(/wiki/lib/styles/../images/error.png) is not within the allowed path(s): (/srv/www/htdocs/example/www.example.com/:/mnt/php/upload:/usr/share/php:/var/lib/php) in <b>/srv/www/htdocs/example/www.example.com/wiki/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Mpdf.php</b> on line <b>11455</b><br />
```

This looks like it is trying to open a URL path instead of a filesystem path.

**Comment by Klap-in** [comment] 2022-01-06 13:22
I guess some paths need to be added to your basedir setting.

**Comment by xi** [comment] 2022-01-06 13:57
No, `/wiki/` definitely does not need to be added to the basedir setting because it does not exist. This path should either be an absolute path that actually exists (e.g. `/srv/www/htdocs/example/www.example.com/wiki/lib/styles/../images/error.png`) or a relative path (e.g. `lib/styles/../images/error.png`).

**Comment by Klap-in** [comment] 2022-10-08 19:33
Duplicate of #453  
please continue there discussion.

**Closed by Klap-in** 2022-10-08 19:33 UTC

**Comment by Klap-in** [comment] 2022-10-08 20:59
Fixed by https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/commit/045bdeeae777ce42f45a16bdb2cf7c7539410dd2
